name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: "golang:1.14"
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Test
        run: make test

  lint:
    runs-on: ubuntu-latest
    container: "golangci/golangci-lint:latest"
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Lint
        run: golangci-lint run --timeout 5m0s

  mod:
    runs-on: ubuntu-latest
    container: "golang:1.14"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tidy
        run: go mod tidy
      - name: Check for changes
        run: git diff --exit-code

  generate:
    runs-on: ubuntu-latest
    container: "golang:1.14"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate
        run: |
          go install github.com/golang/mock/mockgen
          make gen
      - name: Check for changes
        run: git diff --exit-code
